# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs: 
      app-version: ${{ steps.get-version.outputs.app-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

#      - run: echo "APP_VERSION=$(npm pkg get version)" >> "$GITHUB_ENV"
      - name: Get npm package.json version
        id: get-version
        run: echo "app-version=$(npm pkg get version)" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - run: echo "${{ needs.build.outputs.app-version }}"