name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    outputs: 
      app-version: ${{ steps.get-version.outputs.app-version }}

    steps:
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - uses: actions/checkout@v4

      - name: Get npm package.json version
        id: get-version
        run: | 
          APP_VERSION=$(npm pkg get version | tr -d '"')
          echo "app-version=$APP_VERSION" >> "${GITHUB_OUTPUT}"

      - uses: softprops/action-gh-release@v2
        with:
          body: "Binaries for PBMS.Site"
          tag_name: ${{ github.ref }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - run: echo "package:${{ needs.build.outputs.app-version }}"