name: simple ci/cd
on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write

    outputs: 
      app-version: ${{ steps.get-version.outputs.app-version }}

    steps:
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - uses: actions/checkout@v4

      - name: Get npm package.json version
        id: get-version
        run: | 
          APP_VERSION=$(npm pkg get version | tr -d '"')
          echo "app-version=$APP_VERSION" >> "${GITHUB_OUTPUT}"

      - name: Build 
        run: echo "${{ github.sha }}" >> Release.txt
      
      - name: Test
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: Release.txt
          # body: "Binaries for PBMS.Site"
          # tag_name: ${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags')

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - run: echo "package:${{ needs.build.outputs.app-version }}"
